In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [3]:
np.meshgrid(a1, a2)

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]]))

In [4]:
xx, yy = np.meshgrid(a1, a2)

In [5]:
xx

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [6]:
yy

array([[4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

In [7]:
xx.ravel()

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [8]:
yy.ravel()

array([4, 4, 4, 5, 5, 5, 6, 6, 6])

In [70]:
# Cartesian product utilizing np.meshgrid()
np.c_[xx.ravel(), yy.ravel()]

array([[1, 4],
       [2, 4],
       [3, 4],
       [1, 5],
       [2, 5],
       [3, 5],
       [1, 6],
       [2, 6],
       [3, 6]])