In [1]:
import numpy as np

In [2]:
X = np.random.normal(size=(5,3))
rgen = np.random.RandomState(1)
w = rgen.normal(loc=0.0, scale=0.01, size=X.shape[1])
b = np.float64(0.0)
y = np.random.choice(10, size=5)

In [3]:
print(X.shape)
print(w.shape)
print(b.shape)
print(y.shape)

(5, 3)
(3,)
()
(5,)


In [4]:
output = X @ w + b
errors = y - output

### Loop for updating the weights in gradient descent (inefficient)

In [5]:
w

array([ 0.01624345, -0.00611756, -0.00528172])

In [6]:
n = X.shape[0]
p = X.shape[1]
eta = 0.01
for j in range(p):
    for i in range(n):
        w[j] += eta * 2.0 * errors[i] * X[i, j] / n

In [7]:
# Updated weights after one iteration of full batch gradient descent
w

array([0.07721861, 0.07159396, 0.03278597])

### Vectorized version for updating the weights in gradient descent (efficient)

In [9]:
# Initialize the same starting weights as above
rgen = np.random.RandomState(1)
w = rgen.normal(loc=0.0, scale=0.01, size=X.shape[1])

In [12]:
w

array([ 0.01624345, -0.00611756, -0.00528172])

In [13]:
w += eta * 2.0 * X.T @ errors / n

In [15]:
# Updated weights after one iteration of full batch gradient descent
w

array([0.07721861, 0.07159396, 0.03278597])

- As can be seen, the result is the same.